application:
  title: @project.name@
  version: @project.version@

  monitoring:
    scheduledMonitoringRateInMinutes: ${MONITORING_RATE_IN_MIN:15}

  notification:
    senderEmailAddress: ${SENDER_OUTLOOK_ADDRESS:youremail@domain.com}
    senderEmailPassword: ${SENDER_OUTLOOK_PASSWORD:password}

  hierarchyUrl: ${HIERARCHY_URL:http://155.133.131.171:8080/ClassifTraversal/hierarchies/traverse}
  geneMappingUrl: ${GENE_MAPPING_URL:http://155.133.131.171:8080/GENES/gendis/find}
  resourcesAuthKeys: ${RESOURCES_AUTH_KEYS:{"1":"1"}}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:https://auth.ejp.vp.bbmri-eric.eu/auth/realms/EJP/protocol/openid-connect/certs}
          issuer-uri: ${ISSUER_URI:https://auth.ejp.vp.bbmri-eric.eu/auth/realms/EJP}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      # The default value is 'embedded', which only works for in-memory databases.
      # Since we're using a 'non-embedded' database here, we now need to set this to 'always'.
      mode: always

server:
  port: 8095