application:
  title: @project.name@
  version: @project.version@

  monitoring:
    scheduledMonitoringRateInMinutes: ${MONITORING_RATE_IN_MIN:15}

  notification:
    senderEmailAddress: ${SENDER_OUTLOOK_ADDRESS}
    senderEmailPassword: ${SENDER_OUTLOOK_PASSWORD}

  hierarchyUrl: ${HIERARCHY_URL:http://155.133.131.171:8080/ClassifTraversal/hierarchies/traverse}
  geneMappingUrl: ${GENE_MAPPING_URL:http://155.133.131.171:8080/GENES/gendis/find}
  resourcesAuthKeys: ${RESOURCES_AUTH_KEYS}

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:ejp-test}?stringtype=unspecified
    username: ${DB_USER_NAME:ejp-test}
    password: ${DB_USER_PW:ejp-test}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:https://auth.ejp.vp.bbmri-eric.eu/auth/realms/EJP/protocol/openid-connect/certs}
          issuer-uri: ${ISSUER_URI:https://auth.ejp.vp.bbmri-eric.eu/auth/realms/EJP}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      # The default value is 'embedded', which only works for in-memory databases.
      # Since we're using a 'non-embedded' database here, we now need to set this to 'always'.
      mode: always


server:
  port: 8095